title: Crypto Trainer Project
description: Documentation for the Crypto Trainer Project

# Navigation
nav:
  - title: Home
    url: /
  - title: Functional requirements
    url: /functional
  - title: Additional specification
    url: /additional
  - title: DB and Files scheme
    url: /db_files
  - title: Project presentation
    url: /presentation

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default 
